rvm:
  - 2.0.0
  - 1.9.3
  # - jruby-19mode

notifications:
  recipients:
    - support@typuscmf.com

services:
  - mongodb

branches:
  only:
    - master
    - 4-0-stable
    - 3-2-stable
    - 3-1-stable

before_script:
  - psql -c 'create database typus_test;' -U postgres

before_install:
  - git submodule update --init --recursive
  # - gem update --system 1.8.24

env:
  - DB=postgresql
  - DB_USERNAME=postgres
