# zh-CN translations for Typus (template)
# by ZoOL <http://github.com/zhooul>

zh-CN:

  "Actions": "动作"
  "Active": "已激活"
  "Add": "新增"
  "Add %{resource}": "新增 %{resource}"
  "Add new": "新增"
  "Are you sure?": "你是否确认?"
  "Are you sure you want to leave this page?": "你是否确定退出本页面?"
  "Are you sure you want to sign out and end your session?": "你是否确认登出并结束本次会话?"
  "As you're not the admin or the owner of this record you cannot edit it": "你没有修改这条记录的权限"

  "Change %{attribute}?": "改变 %{attribute}"
  "Change password": "修改密码"
  "Checked if active": "检查是否已激活"
  "Click OK to continue, or click Cancel to stay on this page": "点击确定离开页面，或点击取消留在本页面"
  "Create %{resource}": "创建 %{resource}"

  "Dashboard": "信息板"
  "Down": "向下"

  "Edit": "编辑"
  "Enter your email below to create the first user": "输入你的邮箱来创建第一个用户"
  "Error! Typus User or role doesn't exist": "Typus的用户或角色没有创建"

  "False":
  "Filter": "过滤器"
  "Filter by %{attribute}":

  "Go to": "跳转到"

  "I remember my password": "记住密码"
  "If you didn't request a password update, you can ignore this message": "如果你不想更新密码，可以忽略本信息"
  "If you have made any changes to the fields without clicking the Save/Update entry button, your changes will be lost": "如果你没有点击保存/更新按钮，你在本页面的改动将失效"
  "Inactive": "未激活"

  "Last few days": "最近几天"
  "Last 30 days": "最近一个月"
  "Last 7 days": "最近一周"
  "List": "列表"
  "Logged as": "登录为"
  "Login": "登录"

  "New": "新建"
  "New %{resource}": "新建 %{resource}"
  "Next": "下一页"
  "No %{resources} found": " 没有找到 %{resources}"

  "Options": "选项"

  "Password recovery link sent to your email": "重置密码链接发送到了你的邮箱"
  "Previous": "上一页"

  "Record moved %{to}": "记录移动到"
  "Recover password": "恢复密码"
  "Remove": "删除"
  "Remove %{attribute}": "删除 %{attribute}"
  "Remove %{resource}?": "删除 %{resource}"
  "Remove filter": "删除过滤器"
  "Remove search": "删除搜索条件"
  "Reset password": "重置密码"
  "Resources": "资源"

  "Save %{resource}": "保存 %{resource}"
  "Search": "搜索"
  "Search by": 
  "Send us feedback": "向我们发送反馈"
  "Setup": "设置"
  "Show": "显示"
  "Show %{resource}": "显示 %{resource}"
  "Sign in": "登录"
  "Sign out": "登出"
  "Sign up": "注册"
  "Submit a bug report": "发送错误汇报"
  "System Users Administration": "系统用户管理员"

  "That doesn't seem like a valid email address": "不合法的邮箱地址"
  "Today": "今天"
  "Toggle is disabled": "触发器被禁用"
  "True":

  "Unrelate %{resource}?":
  "Up": "向上"

  "View all %{attribute}": "显示所有 %{attribute}"
  "View site": "访问网站"

  "You're adding a new %{resource_from}": "你正在添加新 %{resource_from}"
  "You're adding a new %{resource_from} to %{resource_to}": "你正在添加新 %{resource_from} 和 %{resource_to} 关联"
  "You're not allowed to toggle status": "你不被允许改变状态"
  "You're not allowed to remove Typus Users": "你不被允许删除Typus用户"
  "You're updating a %{resource_from}": "你正在更新 %{resource_from}"
  "You're updating a %{resource_from} for %{resource_to}": "你正在更新与 %{resource_to} 关联的 %{resource_from}  "
  "You can update your password at": "你可以更新你的密码"
  "You can't change your role": "你不能修改你的角色"
  "You can't remove yourself": "你不能删除自己"
  "You can't toggle your status": "你不能修改自己的状态"

  "%{attachment} can't be removed": "%{attachment} 不能被删除"
  "%{attachment} removed": "%{attachment} 已经删除"
  "%{current_user_role} is not able to perform this action. (%{action})": "%{current_user_role} 不能执行这个动作. (%{action})"
  "%{model} filtered by %{filtered_by}": "%{model} 通过 %{filtered_by} 过滤"
  "%{model} successfully created": "%{model} 创建成功"
  "%{model} successfully removed": "%{model} 删除成功"
  "%{model} successfully updated": "%{model} 更新成功"
  "%{model_a} successfully assigned to %{model_b}": "%{model_a} 成功分配给 %{model_b}"
